package com.springboot.mapper;

import com.springboot.model.SysPermissions;

public interface SysPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated
     */
    int insert(SysPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated
     */
    int insertSelective(SysPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated
     */
    SysPermissions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysPermissions record);
}