package com.springboot.mapper;

import com.springboot.model.SysUsers;

import java.util.List;
import java.util.Set;

public interface SysUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated
     */
    int insert(SysUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated
     */
    int insertSelective(SysUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated
     */
    SysUsers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUsers record);

    /**
     * 根据用户名查找用户信息
     * @param username 用户名
     * @return
     */
    SysUsers findByUsername(String username);

    /**
     * 查找用户角色信息
     * @param username 用户名
     * @return
     */
    List<String> findRoles(String username);

    /**
     * 查找用户权限信息
     * @param username 用户名
     * @return
     */
    List<String> findPermissions(String username);
}