package com.springboot.mapper;

import com.springboot.model.SysUsersRolesKey;

public interface SysUsersRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SysUsersRolesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int insert(SysUsersRolesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int insertSelective(SysUsersRolesKey record);
}