server:
  port: 8000
spring:
  application:
    name: shiro-chapter9
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///shiro1
name: xiaohong
password: xiaohong