spring:
  application:
    name: eureka-server
server:
  port: 8000
eureka:
  instance:
    hostname: server1
  client:
    register-with-eureka: false    #由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    fetch-registry: false #由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
    serviceUrl:
      defaultZone: http://xiaoxiao1:xiaoxiao1@server2:8001/eureka/,http://xiaoxiao2:xiaoxiao2@server3:8005/eureka/
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false  #关闭自我保护
security:
  basic:
    enabled: true  #开启认证
  user:
    name: xiaoxiao
    password: xiaoxiao

