package com.springboot.model;

public class SysRolesPermissionsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles_permissions.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles_permissions.permission_id
     *
     * @mbggenerated
     */
    private Long permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles_permissions.role_id
     *
     * @return the value of sys_roles_permissions.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles_permissions.role_id
     *
     * @param roleId the value for sys_roles_permissions.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles_permissions.permission_id
     *
     * @return the value of sys_roles_permissions.permission_id
     *
     * @mbggenerated
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles_permissions.permission_id
     *
     * @param permissionId the value for sys_roles_permissions.permission_id
     *
     * @mbggenerated
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }
}